/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class GetPinnedFileSizeBytesTResponse implements org.apache.thrift.TBase<GetPinnedFileSizeBytesTResponse, GetPinnedFileSizeBytesTResponse._Fields>, java.io.Serializable, Cloneable, Comparable<GetPinnedFileSizeBytesTResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetPinnedFileSizeBytesTResponse");

  private static final org.apache.thrift.protocol.TField PINNED_FILE_SIZE_BYTE_FIELD_DESC = new org.apache.thrift.protocol.TField("pinnedFileSizeByte", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetPinnedFileSizeBytesTResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetPinnedFileSizeBytesTResponseTupleSchemeFactory());
  }

  private long pinnedFileSizeByte; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PINNED_FILE_SIZE_BYTE((short)1, "pinnedFileSizeByte");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PINNED_FILE_SIZE_BYTE
          return PINNED_FILE_SIZE_BYTE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PINNEDFILESIZEBYTE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PINNED_FILE_SIZE_BYTE, new org.apache.thrift.meta_data.FieldMetaData("pinnedFileSizeByte", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetPinnedFileSizeBytesTResponse.class, metaDataMap);
  }

  public GetPinnedFileSizeBytesTResponse() {
  }

  public GetPinnedFileSizeBytesTResponse(
    long pinnedFileSizeByte)
  {
    this();
    this.pinnedFileSizeByte = pinnedFileSizeByte;
    setPinnedFileSizeByteIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetPinnedFileSizeBytesTResponse(GetPinnedFileSizeBytesTResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.pinnedFileSizeByte = other.pinnedFileSizeByte;
  }

  public GetPinnedFileSizeBytesTResponse deepCopy() {
    return new GetPinnedFileSizeBytesTResponse(this);
  }

  @Override
  public void clear() {
    setPinnedFileSizeByteIsSet(false);
    this.pinnedFileSizeByte = 0;
  }

  public long getPinnedFileSizeByte() {
    return this.pinnedFileSizeByte;
  }

  public GetPinnedFileSizeBytesTResponse setPinnedFileSizeByte(long pinnedFileSizeByte) {
    this.pinnedFileSizeByte = pinnedFileSizeByte;
    setPinnedFileSizeByteIsSet(true);
    return this;
  }

  public void unsetPinnedFileSizeByte() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PINNEDFILESIZEBYTE_ISSET_ID);
  }

  /** Returns true if field pinnedFileSizeByte is set (has been assigned a value) and false otherwise */
  public boolean isSetPinnedFileSizeByte() {
    return EncodingUtils.testBit(__isset_bitfield, __PINNEDFILESIZEBYTE_ISSET_ID);
  }

  public void setPinnedFileSizeByteIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PINNEDFILESIZEBYTE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PINNED_FILE_SIZE_BYTE:
      if (value == null) {
        unsetPinnedFileSizeByte();
      } else {
        setPinnedFileSizeByte((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PINNED_FILE_SIZE_BYTE:
      return getPinnedFileSizeByte();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PINNED_FILE_SIZE_BYTE:
      return isSetPinnedFileSizeByte();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetPinnedFileSizeBytesTResponse)
      return this.equals((GetPinnedFileSizeBytesTResponse)that);
    return false;
  }

  public boolean equals(GetPinnedFileSizeBytesTResponse that) {
    if (that == null)
      return false;

    boolean this_present_pinnedFileSizeByte = true;
    boolean that_present_pinnedFileSizeByte = true;
    if (this_present_pinnedFileSizeByte || that_present_pinnedFileSizeByte) {
      if (!(this_present_pinnedFileSizeByte && that_present_pinnedFileSizeByte))
        return false;
      if (this.pinnedFileSizeByte != that.pinnedFileSizeByte)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_pinnedFileSizeByte = true;
    list.add(present_pinnedFileSizeByte);
    if (present_pinnedFileSizeByte)
      list.add(pinnedFileSizeByte);

    return list.hashCode();
  }

  @Override
  public int compareTo(GetPinnedFileSizeBytesTResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPinnedFileSizeByte()).compareTo(other.isSetPinnedFileSizeByte());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPinnedFileSizeByte()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pinnedFileSizeByte, other.pinnedFileSizeByte);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetPinnedFileSizeBytesTResponse(");
    boolean first = true;

    sb.append("pinnedFileSizeByte:");
    sb.append(this.pinnedFileSizeByte);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetPinnedFileSizeBytesTResponseStandardSchemeFactory implements SchemeFactory {
    public GetPinnedFileSizeBytesTResponseStandardScheme getScheme() {
      return new GetPinnedFileSizeBytesTResponseStandardScheme();
    }
  }

  private static class GetPinnedFileSizeBytesTResponseStandardScheme extends StandardScheme<GetPinnedFileSizeBytesTResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetPinnedFileSizeBytesTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PINNED_FILE_SIZE_BYTE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.pinnedFileSizeByte = iprot.readI64();
              struct.setPinnedFileSizeByteIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetPinnedFileSizeBytesTResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PINNED_FILE_SIZE_BYTE_FIELD_DESC);
      oprot.writeI64(struct.pinnedFileSizeByte);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetPinnedFileSizeBytesTResponseTupleSchemeFactory implements SchemeFactory {
    public GetPinnedFileSizeBytesTResponseTupleScheme getScheme() {
      return new GetPinnedFileSizeBytesTResponseTupleScheme();
    }
  }

  private static class GetPinnedFileSizeBytesTResponseTupleScheme extends TupleScheme<GetPinnedFileSizeBytesTResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetPinnedFileSizeBytesTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPinnedFileSizeByte()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPinnedFileSizeByte()) {
        oprot.writeI64(struct.pinnedFileSizeByte);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetPinnedFileSizeBytesTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.pinnedFileSizeByte = iprot.readI64();
        struct.setPinnedFileSizeByteIsSet(true);
      }
    }
  }

}

