/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class GetWorkerInfoListforWriteTResponse implements org.apache.thrift.TBase<GetWorkerInfoListforWriteTResponse, GetWorkerInfoListforWriteTResponse._Fields>, java.io.Serializable, Cloneable, Comparable<GetWorkerInfoListforWriteTResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetWorkerInfoListforWriteTResponse");

  private static final org.apache.thrift.protocol.TField WORKER_INFO_LISTFOR_WRITE_FIELD_DESC = new org.apache.thrift.protocol.TField("workerInfoListforWrite", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetWorkerInfoListforWriteTResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetWorkerInfoListforWriteTResponseTupleSchemeFactory());
  }

  private List<WorkerInfo> workerInfoListforWrite; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WORKER_INFO_LISTFOR_WRITE((short)1, "workerInfoListforWrite");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WORKER_INFO_LISTFOR_WRITE
          return WORKER_INFO_LISTFOR_WRITE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WORKER_INFO_LISTFOR_WRITE, new org.apache.thrift.meta_data.FieldMetaData("workerInfoListforWrite", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, WorkerInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetWorkerInfoListforWriteTResponse.class, metaDataMap);
  }

  public GetWorkerInfoListforWriteTResponse() {
  }

  public GetWorkerInfoListforWriteTResponse(
    List<WorkerInfo> workerInfoListforWrite)
  {
    this();
    this.workerInfoListforWrite = workerInfoListforWrite;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetWorkerInfoListforWriteTResponse(GetWorkerInfoListforWriteTResponse other) {
    if (other.isSetWorkerInfoListforWrite()) {
      List<WorkerInfo> __this__workerInfoListforWrite = new ArrayList<WorkerInfo>(other.workerInfoListforWrite.size());
      for (WorkerInfo other_element : other.workerInfoListforWrite) {
        __this__workerInfoListforWrite.add(new WorkerInfo(other_element));
      }
      this.workerInfoListforWrite = __this__workerInfoListforWrite;
    }
  }

  public GetWorkerInfoListforWriteTResponse deepCopy() {
    return new GetWorkerInfoListforWriteTResponse(this);
  }

  @Override
  public void clear() {
    this.workerInfoListforWrite = null;
  }

  public int getWorkerInfoListforWriteSize() {
    return (this.workerInfoListforWrite == null) ? 0 : this.workerInfoListforWrite.size();
  }

  public java.util.Iterator<WorkerInfo> getWorkerInfoListforWriteIterator() {
    return (this.workerInfoListforWrite == null) ? null : this.workerInfoListforWrite.iterator();
  }

  public void addToWorkerInfoListforWrite(WorkerInfo elem) {
    if (this.workerInfoListforWrite == null) {
      this.workerInfoListforWrite = new ArrayList<WorkerInfo>();
    }
    this.workerInfoListforWrite.add(elem);
  }

  public List<WorkerInfo> getWorkerInfoListforWrite() {
    return this.workerInfoListforWrite;
  }

  public GetWorkerInfoListforWriteTResponse setWorkerInfoListforWrite(List<WorkerInfo> workerInfoListforWrite) {
    this.workerInfoListforWrite = workerInfoListforWrite;
    return this;
  }

  public void unsetWorkerInfoListforWrite() {
    this.workerInfoListforWrite = null;
  }

  /** Returns true if field workerInfoListforWrite is set (has been assigned a value) and false otherwise */
  public boolean isSetWorkerInfoListforWrite() {
    return this.workerInfoListforWrite != null;
  }

  public void setWorkerInfoListforWriteIsSet(boolean value) {
    if (!value) {
      this.workerInfoListforWrite = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case WORKER_INFO_LISTFOR_WRITE:
      if (value == null) {
        unsetWorkerInfoListforWrite();
      } else {
        setWorkerInfoListforWrite((List<WorkerInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case WORKER_INFO_LISTFOR_WRITE:
      return getWorkerInfoListforWrite();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case WORKER_INFO_LISTFOR_WRITE:
      return isSetWorkerInfoListforWrite();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetWorkerInfoListforWriteTResponse)
      return this.equals((GetWorkerInfoListforWriteTResponse)that);
    return false;
  }

  public boolean equals(GetWorkerInfoListforWriteTResponse that) {
    if (that == null)
      return false;

    boolean this_present_workerInfoListforWrite = true && this.isSetWorkerInfoListforWrite();
    boolean that_present_workerInfoListforWrite = true && that.isSetWorkerInfoListforWrite();
    if (this_present_workerInfoListforWrite || that_present_workerInfoListforWrite) {
      if (!(this_present_workerInfoListforWrite && that_present_workerInfoListforWrite))
        return false;
      if (!this.workerInfoListforWrite.equals(that.workerInfoListforWrite))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_workerInfoListforWrite = true && (isSetWorkerInfoListforWrite());
    list.add(present_workerInfoListforWrite);
    if (present_workerInfoListforWrite)
      list.add(workerInfoListforWrite);

    return list.hashCode();
  }

  @Override
  public int compareTo(GetWorkerInfoListforWriteTResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetWorkerInfoListforWrite()).compareTo(other.isSetWorkerInfoListforWrite());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWorkerInfoListforWrite()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.workerInfoListforWrite, other.workerInfoListforWrite);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetWorkerInfoListforWriteTResponse(");
    boolean first = true;

    sb.append("workerInfoListforWrite:");
    if (this.workerInfoListforWrite == null) {
      sb.append("null");
    } else {
      sb.append(this.workerInfoListforWrite);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetWorkerInfoListforWriteTResponseStandardSchemeFactory implements SchemeFactory {
    public GetWorkerInfoListforWriteTResponseStandardScheme getScheme() {
      return new GetWorkerInfoListforWriteTResponseStandardScheme();
    }
  }

  private static class GetWorkerInfoListforWriteTResponseStandardScheme extends StandardScheme<GetWorkerInfoListforWriteTResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetWorkerInfoListforWriteTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // WORKER_INFO_LISTFOR_WRITE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.workerInfoListforWrite = new ArrayList<WorkerInfo>(_list8.size);
                WorkerInfo _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new WorkerInfo();
                  _elem9.read(iprot);
                  struct.workerInfoListforWrite.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setWorkerInfoListforWriteIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetWorkerInfoListforWriteTResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.workerInfoListforWrite != null) {
        oprot.writeFieldBegin(WORKER_INFO_LISTFOR_WRITE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.workerInfoListforWrite.size()));
          for (WorkerInfo _iter11 : struct.workerInfoListforWrite)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetWorkerInfoListforWriteTResponseTupleSchemeFactory implements SchemeFactory {
    public GetWorkerInfoListforWriteTResponseTupleScheme getScheme() {
      return new GetWorkerInfoListforWriteTResponseTupleScheme();
    }
  }

  private static class GetWorkerInfoListforWriteTResponseTupleScheme extends TupleScheme<GetWorkerInfoListforWriteTResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetWorkerInfoListforWriteTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetWorkerInfoListforWrite()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetWorkerInfoListforWrite()) {
        {
          oprot.writeI32(struct.workerInfoListforWrite.size());
          for (WorkerInfo _iter12 : struct.workerInfoListforWrite)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetWorkerInfoListforWriteTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.workerInfoListforWrite = new ArrayList<WorkerInfo>(_list13.size);
          WorkerInfo _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new WorkerInfo();
            _elem14.read(iprot);
            struct.workerInfoListforWrite.add(_elem14);
          }
        }
        struct.setWorkerInfoListforWriteIsSet(true);
      }
    }
  }

}

