/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class RemoveWorkerTOptions implements org.apache.thrift.TBase<RemoveWorkerTOptions, RemoveWorkerTOptions._Fields>, java.io.Serializable, Cloneable, Comparable<RemoveWorkerTOptions> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RemoveWorkerTOptions");

  private static final org.apache.thrift.protocol.TField TRANSFER_CACHE_FIELD_DESC = new org.apache.thrift.protocol.TField("transferCache", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField PERSIST_FIELD_DESC = new org.apache.thrift.protocol.TField("persist", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RemoveWorkerTOptionsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RemoveWorkerTOptionsTupleSchemeFactory());
  }

  private boolean transferCache; // optional
  private boolean persist; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRANSFER_CACHE((short)1, "transferCache"),
    PERSIST((short)2, "persist");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRANSFER_CACHE
          return TRANSFER_CACHE;
        case 2: // PERSIST
          return PERSIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TRANSFERCACHE_ISSET_ID = 0;
  private static final int __PERSIST_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.TRANSFER_CACHE,_Fields.PERSIST};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRANSFER_CACHE, new org.apache.thrift.meta_data.FieldMetaData("transferCache", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.PERSIST, new org.apache.thrift.meta_data.FieldMetaData("persist", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RemoveWorkerTOptions.class, metaDataMap);
  }

  public RemoveWorkerTOptions() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RemoveWorkerTOptions(RemoveWorkerTOptions other) {
    __isset_bitfield = other.__isset_bitfield;
    this.transferCache = other.transferCache;
    this.persist = other.persist;
  }

  public RemoveWorkerTOptions deepCopy() {
    return new RemoveWorkerTOptions(this);
  }

  @Override
  public void clear() {
    setTransferCacheIsSet(false);
    this.transferCache = false;
    setPersistIsSet(false);
    this.persist = false;
  }

  public boolean isTransferCache() {
    return this.transferCache;
  }

  public RemoveWorkerTOptions setTransferCache(boolean transferCache) {
    this.transferCache = transferCache;
    setTransferCacheIsSet(true);
    return this;
  }

  public void unsetTransferCache() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TRANSFERCACHE_ISSET_ID);
  }

  /** Returns true if field transferCache is set (has been assigned a value) and false otherwise */
  public boolean isSetTransferCache() {
    return EncodingUtils.testBit(__isset_bitfield, __TRANSFERCACHE_ISSET_ID);
  }

  public void setTransferCacheIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TRANSFERCACHE_ISSET_ID, value);
  }

  public boolean isPersist() {
    return this.persist;
  }

  public RemoveWorkerTOptions setPersist(boolean persist) {
    this.persist = persist;
    setPersistIsSet(true);
    return this;
  }

  public void unsetPersist() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PERSIST_ISSET_ID);
  }

  /** Returns true if field persist is set (has been assigned a value) and false otherwise */
  public boolean isSetPersist() {
    return EncodingUtils.testBit(__isset_bitfield, __PERSIST_ISSET_ID);
  }

  public void setPersistIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PERSIST_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TRANSFER_CACHE:
      if (value == null) {
        unsetTransferCache();
      } else {
        setTransferCache((Boolean)value);
      }
      break;

    case PERSIST:
      if (value == null) {
        unsetPersist();
      } else {
        setPersist((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TRANSFER_CACHE:
      return isTransferCache();

    case PERSIST:
      return isPersist();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TRANSFER_CACHE:
      return isSetTransferCache();
    case PERSIST:
      return isSetPersist();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RemoveWorkerTOptions)
      return this.equals((RemoveWorkerTOptions)that);
    return false;
  }

  public boolean equals(RemoveWorkerTOptions that) {
    if (that == null)
      return false;

    boolean this_present_transferCache = true && this.isSetTransferCache();
    boolean that_present_transferCache = true && that.isSetTransferCache();
    if (this_present_transferCache || that_present_transferCache) {
      if (!(this_present_transferCache && that_present_transferCache))
        return false;
      if (this.transferCache != that.transferCache)
        return false;
    }

    boolean this_present_persist = true && this.isSetPersist();
    boolean that_present_persist = true && that.isSetPersist();
    if (this_present_persist || that_present_persist) {
      if (!(this_present_persist && that_present_persist))
        return false;
      if (this.persist != that.persist)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_transferCache = true && (isSetTransferCache());
    list.add(present_transferCache);
    if (present_transferCache)
      list.add(transferCache);

    boolean present_persist = true && (isSetPersist());
    list.add(present_persist);
    if (present_persist)
      list.add(persist);

    return list.hashCode();
  }

  @Override
  public int compareTo(RemoveWorkerTOptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTransferCache()).compareTo(other.isSetTransferCache());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransferCache()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transferCache, other.transferCache);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPersist()).compareTo(other.isSetPersist());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersist()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.persist, other.persist);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RemoveWorkerTOptions(");
    boolean first = true;

    if (isSetTransferCache()) {
      sb.append("transferCache:");
      sb.append(this.transferCache);
      first = false;
    }
    if (isSetPersist()) {
      if (!first) sb.append(", ");
      sb.append("persist:");
      sb.append(this.persist);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RemoveWorkerTOptionsStandardSchemeFactory implements SchemeFactory {
    public RemoveWorkerTOptionsStandardScheme getScheme() {
      return new RemoveWorkerTOptionsStandardScheme();
    }
  }

  private static class RemoveWorkerTOptionsStandardScheme extends StandardScheme<RemoveWorkerTOptions> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RemoveWorkerTOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRANSFER_CACHE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.transferCache = iprot.readBool();
              struct.setTransferCacheIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PERSIST
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.persist = iprot.readBool();
              struct.setPersistIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RemoveWorkerTOptions struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetTransferCache()) {
        oprot.writeFieldBegin(TRANSFER_CACHE_FIELD_DESC);
        oprot.writeBool(struct.transferCache);
        oprot.writeFieldEnd();
      }
      if (struct.isSetPersist()) {
        oprot.writeFieldBegin(PERSIST_FIELD_DESC);
        oprot.writeBool(struct.persist);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RemoveWorkerTOptionsTupleSchemeFactory implements SchemeFactory {
    public RemoveWorkerTOptionsTupleScheme getScheme() {
      return new RemoveWorkerTOptionsTupleScheme();
    }
  }

  private static class RemoveWorkerTOptionsTupleScheme extends TupleScheme<RemoveWorkerTOptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RemoveWorkerTOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTransferCache()) {
        optionals.set(0);
      }
      if (struct.isSetPersist()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTransferCache()) {
        oprot.writeBool(struct.transferCache);
      }
      if (struct.isSetPersist()) {
        oprot.writeBool(struct.persist);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RemoveWorkerTOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.transferCache = iprot.readBool();
        struct.setTransferCacheIsSet(true);
      }
      if (incoming.get(1)) {
        struct.persist = iprot.readBool();
        struct.setPersistIsSet(true);
      }
    }
  }

}

